export const card = [
  { en_w: "Processor", ru_w: "Процессор", collectionId: 0 },
  { en_w: "Motherboard", ru_w: "Материнская плата", collectionId: 0 },
  { en_w: "Graphics card", ru_w: "Видеокарта", collectionId: 0 },
  { en_w: "Monitor", ru_w: "Монитор", collectionId: 0 },
  { en_w: "Keyboard", ru_w: "Клавиатура", collectionId: 0 },
  { en_w: "Mouse", ru_w: "Мышь", collectionId: 0 },
  { en_w: "Hard drive", ru_w: "Жесткий диск", collectionId: 0 },
  { en_w: "RAM", ru_w: "Оперативная память", collectionId: 0 },
  { en_w: "SSD", ru_w: "Твердотельный накопитель", collectionId: 0 },
  { en_w: "Power supply", ru_w: "Блок питания", collectionId: 0 },
  { en_w: "Cooling fan", ru_w: "Охлаждающий вентилятор", collectionId: 0 },
  { en_w: "USB port", ru_w: "USB-порт", collectionId: 0 },
  { en_w: "Laptop", ru_w: "Ноутбук", collectionId: 0 },
  { en_w: "Desktop", ru_w: "Настольный компьютер", collectionId: 0 },
  { en_w: "Operating system", ru_w: "Операционная система", collectionId: 0 },
  { en_w: "Touchscreen", ru_w: "Сенсорный экран", collectionId: 1 },
  { en_w: "Battery", ru_w: "Батарея", collectionId: 1 },
  { en_w: "Camera", ru_w: "Камера", collectionId: 1 },
  { en_w: "Charger", ru_w: "Зарядное устройство", collectionId: 1 },
  { en_w: "SIM card", ru_w: "СИМ-карта", collectionId: 1 },
  { en_w: "Smartwatch", ru_w: "Умные часы", collectionId: 1 },
  {
    en_w: "Fingerprint sensor",
    ru_w: "Сканер отпечатков пальцев",
    collectionId: 1,
  },
  { en_w: "Face recognition", ru_w: "Распознавание лица", collectionId: 1 },
  { en_w: "Mobile app", ru_w: "Мобильное приложение", collectionId: 1 },
  { en_w: "Screen protector", ru_w: "Защитное стекло", collectionId: 1 },
  { en_w: "Memory card", ru_w: "Карта памяти", collectionId: 1 },
  { en_w: "Headphones", ru_w: "Наушники", collectionId: 1 },
  { en_w: "Bluetooth", ru_w: "Блютуз", collectionId: 1 },
  { en_w: "Wi-Fi", ru_w: "Вай-Фай", collectionId: 1 },
  { en_w: "Power bank", ru_w: "Внешний аккумулятор", collectionId: 1 },
  { en_w: "Case", ru_w: "Чехол", collectionId: 1 },
  { en_w: "Screen resolution", ru_w: "Разрешение экрана", collectionId: 1 },
  { en_w: "Speaker", ru_w: "Динамик", collectionId: 1 },
  { en_w: "Processor speed", ru_w: "Скорость процессора", collectionId: 1 },
  { en_w: "Machine learning", ru_w: "Машинное обучение", collectionId: 2 },
  { en_w: "Neural network", ru_w: "Нейронная сеть", collectionId: 2 },
  { en_w: "Algorithm", ru_w: "Алгоритм", collectionId: 2 },
  { en_w: "Data", ru_w: "Данные", collectionId: 2 },
  { en_w: "Automation", ru_w: "Автоматизация", collectionId: 2 },
  { en_w: "Prediction", ru_w: "Прогнозирование", collectionId: 2 },
  {
    en_w: "Natural language processing",
    ru_w: "Обработка естественного языка",
    collectionId: 2,
  },
  { en_w: "Big data", ru_w: "Большие данные", collectionId: 2 },
  { en_w: "Training", ru_w: "Обучение", collectionId: 2 },
  { en_w: "AI ethics", ru_w: "Этика ИИ", collectionId: 2 },
  { en_w: "Chatbot", ru_w: "Чат-бот", collectionId: 2 },
  { en_w: "Deep learning", ru_w: "Глубокое обучение", collectionId: 2 },
  { en_w: "Computer vision", ru_w: "Компьютерное зрение", collectionId: 2 },
  { en_w: "Robotics", ru_w: "Робототехника", collectionId: 2 },
  { en_w: "Data analysis", ru_w: "Анализ данных", collectionId: 2 },
  { en_w: "Satellite", ru_w: "Спутник", collectionId: 3 },
  { en_w: "Rocket", ru_w: "Ракета", collectionId: 3 },
  { en_w: "Astronaut", ru_w: "Астронавт", collectionId: 3 },
  { en_w: "Space station", ru_w: "Космическая станция", collectionId: 3 },
  { en_w: "Orbit", ru_w: "Орбита", collectionId: 3 },
  { en_w: "Launch pad", ru_w: "Стартовая площадка", collectionId: 3 },
  { en_w: "Telescope", ru_w: "Телескоп", collectionId: 3 },
  { en_w: "Mars rover", ru_w: "Марсоход", collectionId: 3 },
  { en_w: "Space probe", ru_w: "Космический зонд", collectionId: 3 },
  { en_w: "Black hole", ru_w: "Черная дыра", collectionId: 3 },
  { en_w: "Moon landing", ru_w: "Посадка на Луну", collectionId: 3 },
  { en_w: "Space exploration", ru_w: "Исследование космоса", collectionId: 3 },
  { en_w: "Asteroid", ru_w: "Астероид", collectionId: 3 },
  { en_w: "Comet", ru_w: "Комета", collectionId: 3 },
  { en_w: "Gravity", ru_w: "Гравитация", collectionId: 3 },
  { en_w: "Robot", ru_w: "Робот", collectionId: 4 },
  { en_w: "Automation", ru_w: "Автоматизация", collectionId: 4 },
  { en_w: "Sensor", ru_w: "Датчик", collectionId: 4 },
  { en_w: "Actuator", ru_w: "Привод", collectionId: 4 },
  { en_w: "Humanoid robot", ru_w: "Гуманоидный робот", collectionId: 4 },
  { en_w: "Industrial robot", ru_w: "Промышленный робот", collectionId: 4 },
  {
    en_w: "Artificial intelligence",
    ru_w: "Искусственный интеллект",
    collectionId: 4,
  },
  { en_w: "Drone", ru_w: "Дрон", collectionId: 4 },
  { en_w: "Robot arm", ru_w: "Роботизированная рука", collectionId: 4 },
  {
    en_w: "Robotic surgery",
    ru_w: "Роботизированная хирургия",
    collectionId: 4,
  },
  { en_w: "Autonomous vehicle", ru_w: "Автономный транспорт", collectionId: 4 },
  { en_w: "Programming", ru_w: "Программирование", collectionId: 4 },
  { en_w: "3D printing", ru_w: "3D-печать", collectionId: 4 },
  { en_w: "Robot vacuum", ru_w: "Робот-пылесос", collectionId: 4 },
  { en_w: "Control system", ru_w: "Система управления", collectionId: 4 },
  { en_w: "Smart speaker", ru_w: "Умная колонка", collectionId: 5 },
  { en_w: "Thermostat", ru_w: "Термостат", collectionId: 5 },
  { en_w: "Smart light", ru_w: "Умный свет", collectionId: 5 },
  { en_w: "Security camera", ru_w: "Камера безопасности", collectionId: 5 },
  { en_w: "Doorbell camera", ru_w: "Видеозвонок", collectionId: 5 },
  { en_w: "Voice control", ru_w: "Голосовое управление", collectionId: 5 },
  { en_w: "Smart lock", ru_w: "Умный замок", collectionId: 5 },
  { en_w: "Home automation", ru_w: "Автоматизация дома", collectionId: 5 },
  { en_w: "Motion sensor", ru_w: "Датчик движения", collectionId: 5 },
  { en_w: "Energy efficiency", ru_w: "Энергоэффективность", collectionId: 5 },
  { en_w: "Smart plug", ru_w: "Умная розетка", collectionId: 5 },
  { en_w: "Wi-Fi router", ru_w: "Wi-Fi роутер", collectionId: 5 },
  { en_w: "Smoke detector", ru_w: "Датчик дыма", collectionId: 5 },
  { en_w: "Water leak sensor", ru_w: "Датчик утечки воды", collectionId: 5 },
  { en_w: "Smart TV", ru_w: "Умный телевизор", collectionId: 5 },
  { en_w: "Variable", ru_w: "Переменная", collectionId: 6 },
  { en_w: "Loop", ru_w: "Цикл", collectionId: 6 },
  { en_w: "Function", ru_w: "Функция", collectionId: 6 },
  { en_w: "Syntax", ru_w: "Синтаксис", collectionId: 6 },
  { en_w: "Array", ru_w: "Массив", collectionId: 6 },
  { en_w: "String", ru_w: "Строка", collectionId: 6 },
  { en_w: "Debugging", ru_w: "Отладка", collectionId: 6 },
  { en_w: "Compiler", ru_w: "Компилятор", collectionId: 6 },
  { en_w: "Algorithm", ru_w: "Алгоритм", collectionId: 6 },
  { en_w: "Binary", ru_w: "Двоичный код", collectionId: 6 },
  { en_w: "Class", ru_w: "Класс", collectionId: 6 },
  { en_w: "Object", ru_w: "Объект", collectionId: 6 },
  { en_w: "Inheritance", ru_w: "Наследование", collectionId: 6 },
  { en_w: "Recursion", ru_w: "Рекурсия", collectionId: 6 },
  { en_w: "Framework", ru_w: "Фреймворк", collectionId: 6 },
  { en_w: "Homework", ru_w: "Домашнее задание", collectionId: 7 },
  { en_w: "Lecture", ru_w: "Лекция", collectionId: 7 },
  { en_w: "Semester", ru_w: "Семестр", collectionId: 7 },
  { en_w: "Exam", ru_w: "Экзамен", collectionId: 7 },
  { en_w: "Textbook", ru_w: "Учебник", collectionId: 7 },
  { en_w: "Tutor", ru_w: "Репетитор", collectionId: 7 },
  { en_w: "Quiz", ru_w: "Викторина", collectionId: 7 },
  { en_w: "Essay", ru_w: "Эссе", collectionId: 7 },
  { en_w: "Laboratory", ru_w: "Лаборатория", collectionId: 7 },
  { en_w: "Diploma", ru_w: "Диплом", collectionId: 7 },
  { en_w: "Certificate", ru_w: "Сертификат", collectionId: 7 },
  { en_w: "Grade", ru_w: "Оценка", collectionId: 7 },
  { en_w: "Presentation", ru_w: "Презентация", collectionId: 7 },
  { en_w: "Assignment", ru_w: "Задание", collectionId: 7 },
  { en_w: "Curriculum", ru_w: "Учебный план", collectionId: 7 },
  { en_w: "History", ru_w: "История", collectionId: 8 },
  { en_w: "Mathematics", ru_w: "Математика", collectionId: 8 },
  { en_w: "Science", ru_w: "Наука", collectionId: 8 },
  { en_w: "Geography", ru_w: "География", collectionId: 8 },
  { en_w: "Biology", ru_w: "Биология", collectionId: 8 },
  { en_w: "Physics", ru_w: "Физика", collectionId: 8 },
  { en_w: "Chemistry", ru_w: "Химия", collectionId: 8 },
  { en_w: "Literature", ru_w: "Литература", collectionId: 8 },
  { en_w: "Art", ru_w: "Искусство", collectionId: 8 },
  { en_w: "Philosophy", ru_w: "Философия", collectionId: 8 },
  { en_w: "Engineering", ru_w: "Инженерия", collectionId: 8 },
  { en_w: "Grammar", ru_w: "Грамматика", collectionId: 8 },
  { en_w: "Vocabulary", ru_w: "Словарный запас", collectionId: 8 },
  { en_w: "Test", ru_w: "Тест", collectionId: 9 },
  { en_w: "Multiple choice", ru_w: "Множественный выбор", collectionId: 9 },
  { en_w: "Practice", ru_w: "Практика", collectionId: 9 },
  { en_w: "Mock exam", ru_w: "Пробный экзамен", collectionId: 9 },
  { en_w: "Score", ru_w: "Результат", collectionId: 9 },
  { en_w: "Answer", ru_w: "Ответ", collectionId: 9 },
  { en_w: "Question", ru_w: "Вопрос", collectionId: 9 },
  { en_w: "Review", ru_w: "Обзор", collectionId: 9 },
  { en_w: "Cheat sheet", ru_w: "Шпаргалка", collectionId: 9 },
  { en_w: "Results", ru_w: "Результаты", collectionId: 9 },
  { en_w: "Essay exam", ru_w: "Эссе экзамен", collectionId: 9 },
  { en_w: "Mountain", ru_w: "Гора", collectionId: 10 },
  { en_w: "Hiking", ru_w: "Поход", collectionId: 10 },
  { en_w: "Backpack", ru_w: "Рюкзак", collectionId: 10 },
  { en_w: "Trail", ru_w: "Тропа", collectionId: 10 },
  { en_w: "Summit", ru_w: "Вершина", collectionId: 10 },
  { en_w: "Map", ru_w: "Карта", collectionId: 10 },
  { en_w: "Compass", ru_w: "Компас", collectionId: 10 },
  { en_w: "Sleeping bag", ru_w: "Спальный мешок", collectionId: 10 },
  { en_w: "Tent", ru_w: "Палатка", collectionId: 10 },
  { en_w: "Climbing gear", ru_w: "Снаряжение для лазания", collectionId: 10 },
  { en_w: "Altitude", ru_w: "Высота", collectionId: 10 },
  { en_w: "First aid kit", ru_w: "Аптечка", collectionId: 10 },
  { en_w: "Campfire", ru_w: "Костер", collectionId: 10 },
  { en_w: "Rock", ru_w: "Скала", collectionId: 10 },
  { en_w: "Landscape", ru_w: "Пейзаж", collectionId: 10 },
  { en_w: "Beach", ru_w: "Пляж", collectionId: 11 },
  { en_w: "Sunbed", ru_w: "Шезлонг", collectionId: 11 },
  { en_w: "Umbrella", ru_w: "Зонт", collectionId: 11 },
  { en_w: "Swimsuit", ru_w: "Купальник", collectionId: 11 },
  { en_w: "Sandcastle", ru_w: "Песочный замок", collectionId: 11 },
  { en_w: "Towel", ru_w: "Полотенце", collectionId: 11 },
  { en_w: "Waves", ru_w: "Волны", collectionId: 11 },
  { en_w: "Surfboard", ru_w: "Доска для серфинга", collectionId: 11 },
  { en_w: "Snorkeling", ru_w: "Подводное плавание", collectionId: 11 },
  { en_w: "Beach ball", ru_w: "Мяч для пляжа", collectionId: 11 },
  { en_w: "Seashell", ru_w: "Ракушка", collectionId: 11 },
  { en_w: "Sunblock", ru_w: "Солнцезащитный крем", collectionId: 11 },
  { en_w: "Lifeguard", ru_w: "Спасатель", collectionId: 11 },
  { en_w: "Coconut", ru_w: "Кокос", collectionId: 11 },
  { en_w: "Jet ski", ru_w: "Водный мотоцикл", collectionId: 11 },
  { en_w: "Eiffel Tower", ru_w: "Эйфелева башня", collectionId: 12 },
  { en_w: "Colosseum", ru_w: "Колизей", collectionId: 12 },
  { en_w: "Big Ben", ru_w: "Биг Бен", collectionId: 12 },
  { en_w: "Leaning Tower of Pisa", ru_w: "Пизанская башня", collectionId: 12 },
  { en_w: "Louvre", ru_w: "Лувр", collectionId: 12 },
  { en_w: "Venice", ru_w: "Венеция", collectionId: 12 },
  { en_w: "Tower Bridge", ru_w: "Тауэрский мост", collectionId: 12 },
  { en_w: "Buckingham Palace", ru_w: "Букингемский дворец", collectionId: 12 },
  { en_w: "Berlin Wall", ru_w: "Берлинская стена", collectionId: 12 },
  { en_w: "Vatican City", ru_w: "Ватикан", collectionId: 12 },
  { en_w: "Edinburgh Castle", ru_w: "Эдинбургский замок", collectionId: 12 },
  { en_w: "Notre-Dame", ru_w: "Нотр-Дам", collectionId: 12 },
  { en_w: "Santorini", ru_w: "Санторини", collectionId: 12 },
  { en_w: "Alhambra", ru_w: "Альгамбра", collectionId: 12 },
  { en_w: "Stonehenge", ru_w: "Стоунхендж", collectionId: 12 },
  { en_w: "Cruise ship", ru_w: "Круизный лайнер", collectionId: 13 },
  { en_w: "Cabin", ru_w: "Каюта", collectionId: 13 },
  { en_w: "Captain", ru_w: "Капитан", collectionId: 13 },
  { en_w: "Deck", ru_w: "Палуба", collectionId: 13 },
  { en_w: "Lifejacket", ru_w: "Спасательный жилет", collectionId: 13 },
  { en_w: "Port", ru_w: "Порт", collectionId: 13 },
  { en_w: "Ocean", ru_w: "Океан", collectionId: 13 },
  { en_w: "Excursion", ru_w: "Экскурсия", collectionId: 13 },
  { en_w: "Buffet", ru_w: "Шведский стол", collectionId: 13 },
  { en_w: "Entertainment", ru_w: "Развлечения", collectionId: 13 },
  { en_w: "Crew", ru_w: "Экипаж", collectionId: 13 },
  { en_w: "Itinerary", ru_w: "Маршрут", collectionId: 13 },
  { en_w: "Lighthouse", ru_w: "Маяк", collectionId: 13 },
  { en_w: "Swimming pool", ru_w: "Бассейн", collectionId: 13 },
  { en_w: "Sunset", ru_w: "Закат", collectionId: 13 },
  { en_w: "Safari", ru_w: "Сафари", collectionId: 14 },
  { en_w: "Jungle", ru_w: "Джунгли", collectionId: 14 },
  { en_w: "Elephant", ru_w: "Слон", collectionId: 14 },
  { en_w: "Camel", ru_w: "Верблюд", collectionId: 14 },
  { en_w: "Pyramid", ru_w: "Пирамида", collectionId: 14 },
  { en_w: "Tropical", ru_w: "Тропический", collectionId: 14 },
  { en_w: "Temple", ru_w: "Храм", collectionId: 14 },
  { en_w: "Rainforest", ru_w: "Тропический лес", collectionId: 14 },
  { en_w: "Island", ru_w: "Остров", collectionId: 14 },
  { en_w: "Coral reef", ru_w: "Коралловый риф", collectionId: 14 },
  { en_w: "Safari guide", ru_w: "Гид по сафари", collectionId: 14 },
  { en_w: "Wildlife", ru_w: "Дикая природа", collectionId: 14 },
  { en_w: "Volcano", ru_w: "Вулкан", collectionId: 14 },
  { en_w: "Cultural tour", ru_w: "Культурный тур", collectionId: 14 },
  { en_w: "Traditional dance", ru_w: "Традиционный танец", collectionId: 14 },
  { en_w: "Respawn", ru_w: "Респавн", collectionId: 15 },
  { en_w: "Noob", ru_w: "Нуб", collectionId: 15 },
  { en_w: "GG", ru_w: "Хорошая игра", collectionId: 15 },
  { en_w: "AFK", ru_w: "Отошел от клавиатуры", collectionId: 15 },
  { en_w: "Buff", ru_w: "Усиление", collectionId: 15 },
  { en_w: "Debuff", ru_w: "Ослабление", collectionId: 15 },
  { en_w: "PvP", ru_w: "Игрок против игрока", collectionId: 15 },
  { en_w: "PvE", ru_w: "Игрок против окружения", collectionId: 15 },
  { en_w: "Grind", ru_w: "Гринд", collectionId: 15 },
  { en_w: "Loot", ru_w: "Добыча", collectionId: 15 },
  { en_w: "Quest", ru_w: "Задание", collectionId: 15 },
  { en_w: "Boss", ru_w: "Босс", collectionId: 15 },
  { en_w: "Camp", ru_w: "Кемп", collectionId: 15 },
  { en_w: "Clan", ru_w: "Клан", collectionId: 15 },
  { en_w: "Carry", ru_w: "Керри", collectionId: 15 },
  { en_w: "Strat", ru_w: "Стратегия", collectionId: 15 },
  { en_w: "Patch", ru_w: "Патч", collectionId: 15 },
  { en_w: "Meta", ru_w: "Мета", collectionId: 15 },
  { en_w: "Tilt", ru_w: "Тильт", collectionId: 15 },
  { en_w: "Farm", ru_w: "Фарм", collectionId: 15 },
  { en_w: "Pro", ru_w: "Профессионал", collectionId: 16 },
  { en_w: "Ragequit", ru_w: "Выход в гневе", collectionId: 16 },
  { en_w: "Clutch", ru_w: "Клатч", collectionId: 16 },
  { en_w: "Frag", ru_w: "Фраг", collectionId: 16 },
  { en_w: "Headshot", ru_w: "Выстрел в голову", collectionId: 16 },
  { en_w: "Sniper", ru_w: "Снайпер", collectionId: 16 },
  { en_w: "Support", ru_w: "Поддержка", collectionId: 16 },
  { en_w: "Tank", ru_w: "Танк", collectionId: 16 },
  { en_w: "ADC", ru_w: "Атака на дистанции", collectionId: 16 },
  { en_w: "Mid", ru_w: "Мид", collectionId: 16 },
  { en_w: "Jungle", ru_w: "Джангл", collectionId: 16 },
  { en_w: "Rush", ru_w: "Раш", collectionId: 16 },
  { en_w: "FPS", ru_w: "Шутер от первого лица", collectionId: 16 },
  { en_w: "TDM", ru_w: "Командный бой насмерть", collectionId: 16 },
  { en_w: "LAN", ru_w: "Локальная сеть", collectionId: 16 },
  { en_w: "MMR", ru_w: "Рейтинг матчей", collectionId: 16 },
  { en_w: "Cooldown", ru_w: "Перезарядка", collectionId: 16 },
  { en_w: "Skillshot", ru_w: "Скиллшот", collectionId: 16 },
  { en_w: "Outplay", ru_w: "Переиграть", collectionId: 16 },
  { en_w: "Football", ru_w: "Футбол", collectionId: 17 },
  { en_w: "Goalkeeper", ru_w: "Вратарь", collectionId: 17 },
  { en_w: "Striker", ru_w: "Нападающий", collectionId: 17 },
  { en_w: "Midfielder", ru_w: "Полузащитник", collectionId: 17 },
  { en_w: "Defender", ru_w: "Защитник", collectionId: 17 },
  { en_w: "Offside", ru_w: "Офсайд", collectionId: 17 },
  { en_w: "Penalty", ru_w: "Пенальти", collectionId: 17 },
  { en_w: "Corner kick", ru_w: "Угловой удар", collectionId: 17 },
  { en_w: "Free kick", ru_w: "Штрафной удар", collectionId: 17 },
  { en_w: "Yellow card", ru_w: "Желтая карточка", collectionId: 17 },
  { en_w: "Red card", ru_w: "Красная карточка", collectionId: 17 },
  { en_w: "Substitute", ru_w: "Замена", collectionId: 17 },
  { en_w: "Dribbling", ru_w: "Дриблинг", collectionId: 17 },
  { en_w: "Header", ru_w: "Удар головой", collectionId: 17 },
  { en_w: "Match", ru_w: "Матч", collectionId: 17 },
  { en_w: "Basketball", ru_w: "Баскетбол", collectionId: 18 },
  { en_w: "Dribble", ru_w: "Ведение мяча", collectionId: 18 },
  { en_w: "Three-pointer", ru_w: "Трехочковый", collectionId: 18 },
  { en_w: "Slam dunk", ru_w: "Слэм-данк", collectionId: 18 },
  { en_w: "Free throw", ru_w: "Штрафной бросок", collectionId: 18 },
  { en_w: "Rebound", ru_w: "Подбор", collectionId: 18 },
  { en_w: "Block", ru_w: "Блок-шот", collectionId: 18 },
  { en_w: "Point guard", ru_w: "Разыгрывающий защитник", collectionId: 18 },
  { en_w: "Shooting guard", ru_w: "Атакующий защитник", collectionId: 18 },
  { en_w: "Small forward", ru_w: "Лёгкий форвард", collectionId: 18 },
  { en_w: "Power forward", ru_w: "Тяжелый форвард", collectionId: 18 },
  { en_w: "Center", ru_w: "Центровой", collectionId: 18 },
  { en_w: "Court", ru_w: "Площадка", collectionId: 18 },
  { en_w: "Timeout", ru_w: "Тайм-аут", collectionId: 18 },
  { en_w: "Jogging", ru_w: "Бег трусцой", collectionId: 19 },
  { en_w: "Sprint", ru_w: "Спринт", collectionId: 19 },
  { en_w: "Marathon", ru_w: "Марафон", collectionId: 19 },
  { en_w: "Track", ru_w: "Беговая дорожка", collectionId: 19 },
  { en_w: "Pace", ru_w: "Темп", collectionId: 19 },
  { en_w: "Endurance", ru_w: "Выносливость", collectionId: 19 },
  { en_w: "Stretching", ru_w: "Растяжка", collectionId: 19 },
  { en_w: "Shoes", ru_w: "Кроссовки", collectionId: 19 },
  {
    en_w: "Interval training",
    ru_w: "Интервальная тренировка",
    collectionId: 19,
  },
  { en_w: "Finish line", ru_w: "Финишная линия", collectionId: 19 },
  { en_w: "Runner's high", ru_w: "Эйфория бегуна", collectionId: 19 },
  { en_w: "Hydration", ru_w: "Гидратация", collectionId: 19 },
  { en_w: "Training plan", ru_w: "План тренировок", collectionId: 19 },
  { en_w: "Personal best", ru_w: "Личный рекорд", collectionId: 19 },
  { en_w: "Meditation", ru_w: "Медитация", collectionId: 20 },
  { en_w: "Asana", ru_w: "Асана", collectionId: 20 },
  { en_w: "Balance", ru_w: "Баланс", collectionId: 20 },
  { en_w: "Flexibility", ru_w: "Гибкость", collectionId: 20 },
  { en_w: "Pose", ru_w: "Позы", collectionId: 20 },
  { en_w: "Flow", ru_w: "Поток", collectionId: 20 },
  { en_w: "Namaste", ru_w: "Намасте", collectionId: 20 },
  { en_w: "Chakra", ru_w: "Чакра", collectionId: 20 },
  { en_w: "Mindfulness", ru_w: "Осознанность", collectionId: 20 },
  { en_w: "Breathing", ru_w: "Дыхание", collectionId: 20 },
  { en_w: "Energy", ru_w: "Энергия", collectionId: 20 },
  { en_w: "Relaxation", ru_w: "Расслабление", collectionId: 20 },
  { en_w: "Posture", ru_w: "Осанка", collectionId: 20 },
  { en_w: "Harmony", ru_w: "Гармония", collectionId: 20 },
  { en_w: "Rock climbing", ru_w: "Скалолазание", collectionId: 21 },
  { en_w: "Harness", ru_w: "Страховка", collectionId: 21 },
  { en_w: "Carabiner", ru_w: "Карабин", collectionId: 21 },
  { en_w: "Belay", ru_w: "Страховка (при лазании)", collectionId: 21 },
  { en_w: "Grip", ru_w: "Хват", collectionId: 21 },
  { en_w: "Chalk", ru_w: "Магнезия", collectionId: 21 },
  { en_w: "Route", ru_w: "Маршрут", collectionId: 21 },
  { en_w: "Anchor", ru_w: "Анкер", collectionId: 21 },
  { en_w: "Crux", ru_w: "Ключевой участок", collectionId: 21 },
  {
    en_w: "Lead climbing",
    ru_w: "Лазание с верхней страховкой",
    collectionId: 21,
  },
  { en_w: "Bouldering", ru_w: "Боулдеринг", collectionId: 21 },
  { en_w: "Climbing shoes", ru_w: "Скальные туфли", collectionId: 21 },
  { en_w: "Top rope", ru_w: "Топ-роуп", collectionId: 21 },
  { en_w: "Safety rope", ru_w: "Страховочная веревка", collectionId: 21 },
  { en_w: "Cycling", ru_w: "Велоспорт", collectionId: 22 },
  { en_w: "Helmet", ru_w: "Шлем", collectionId: 22 },
  { en_w: "Bike", ru_w: "Велосипед", collectionId: 22 },
  { en_w: "Pedals", ru_w: "Педали", collectionId: 22 },
  { en_w: "Handlebars", ru_w: "Руль", collectionId: 22 },
  { en_w: "Gear", ru_w: "Передача", collectionId: 22 },
  { en_w: "Chain", ru_w: "Цепь", collectionId: 22 },
  { en_w: "Brakes", ru_w: "Тормоза", collectionId: 22 },
  { en_w: "Race", ru_w: "Гонка", collectionId: 22 },
  { en_w: "Trail", ru_w: "Тропа", collectionId: 22 },
  { en_w: "Speed", ru_w: "Скорость", collectionId: 22 },
  { en_w: "Cyclist", ru_w: "Велосипедист", collectionId: 22 },
  { en_w: "Tour", ru_w: "Тур", collectionId: 22 },
  { en_w: "Road bike", ru_w: "Шоссейный велосипед", collectionId: 22 },
  { en_w: "Mountain bike", ru_w: "Горный велосипед", collectionId: 22 },
].map((obj, index) => ({ id: index, ...obj }));

export const categories = [
  {
    name: "Технологии",
  },
  {
    name: "Учеба",
  },
  {
    name: "Путешествия",
  },
  {
    name: "Игры",
  },
  {
    name: "Спорт",
  },
].map((obj, index) => ({ id: index, ...obj }));

export const collections = [
  { name: "Компьютеры", categoryId: 0 },
  { name: "Смартфоны", categoryId: 0 },
  { name: "Искусственный интеллект", categoryId: 0 },
  { name: "Космические технологии", categoryId: 0 },
  { name: "Робототехника", categoryId: 0 },
  { name: "Умный дом", categoryId: 0 },
  { name: "Программирование", categoryId: 1 },
  { name: "Школы и университеты", categoryId: 1 },
  { name: "Школьные предметы", categoryId: 1 },
  { name: "Экзамены и тесты", categoryId: 1 },
  { name: "Горные походы", categoryId: 2 },
  { name: "Пляжный отдых", categoryId: 2 },
  { name: "Достопримечательности Европы", categoryId: 2 },
  { name: "Круизы", categoryId: 2 },
  { name: "Экзотические страны", categoryId: 2 },
  { name: "Видеоигры", categoryId: 3 },
  { name: "Киберспорт", categoryId: 3 },
  { name: "Футбол", categoryId: 4 },
  { name: "Баскетбол", categoryId: 4 },
  { name: "Бег", categoryId: 4 },
  { name: "Йога", categoryId: 4 },
  { name: "Скалолазание", categoryId: 4 },
  { name: "Велоспорт", categoryId: 4 },
].map((obj, index) => ({ id: index, ...obj }));
