export const card = [
  { en_w: "Cat", ru_w: "Кошка" },
  { en_w: "House", ru_w: "Дом" },
  { en_w: "Dog", ru_w: "Собака" },
  { en_w: "Tree", ru_w: "Дерево" },
  { en_w: "Book", ru_w: "Книга" },
  { en_w: "Car", ru_w: "Машина" },
  { en_w: "Water", ru_w: "Вода" },
  { en_w: "Chair", ru_w: "Стул" },
  { en_w: "Table", ru_w: "Стол" },
  { en_w: "Sun", ru_w: "Солнце" },
  { en_w: "Moon", ru_w: "Луна" },
  { en_w: "Bird", ru_w: "Птица" },
  { en_w: "Fish", ru_w: "Рыба" },
  { en_w: "Flower", ru_w: "Цветок" },
  { en_w: "Friend", ru_w: "Друг" },
  { en_w: "21", ru_w: "-21" },
  { en_w: "22", ru_w: "-22" },
  { en_w: "23", ru_w: "-23" },
  { en_w: "31", ru_w: "-31" },
  { en_w: "32", ru_w: "-32" },
  { en_w: "33", ru_w: "-33" },
].map((obj, index) => ({ id: index + 1, ...obj }));
